language: python
python:
- '3.4'
install:
- pip install -r requirements_for_test.txt
- npm install
- npm run frontend-build:production
script:
- ./scripts/run_tests.sh
deploy:
  provider: heroku
  app:
    master: notify-admin
  api_key:
    secure: ZOmX4V3I+Qy2T5GaoKEDJG9keG1eYkKUwLiFkQWGC+Sz0vmalzdsLJXeldzVUN3vpTGCzopkWiNNRxdTrEzZNHQh7RtnroIaPPyZQqG6la/OFljhE2CwgpqyocbSB/ZGtDy6t32t7JzX0rpk69Ptxtt4TITXrb4C87GiwzDOGaIqVziiqxy7FfoKgpnlayLpDnlywVlQxWmzuwyDDtqts2mGbm8ChcOMDQse+7rHrro8K12kTM9JaBqRe10SBZfdKzmlf+Linc77JJdpL8OYUntbl8xDFvPvRvQGUaZSTmZ6FrZpDF+yUgwOVKwekZI0cIhcaZkAU2fvYks2E51ygF1UhesRS27cCfrkrXeLHzibhdEtLqAgTDUzbQhd8zjmc5i+EvkCuzLiuOqdo8QSnYZjPpdLtQXsjy7YlrSj0wwq70BLfttmjCMOqc0NjS19WA9YiK1XqannZavyfXAx3v/x6BR95bET8QfXaNCMTv6UQwggkiWst3s/vckT8y9XKX+7gTSBbgBey8VXpVFuTBmK6aiiQzDIFK94tfsoVXZZJDJgJgBe+Ca8BOnBuphs4pNa3aetkT4eqmj51kAfCH5XTS5oYPF5IwnBOXrcEU0woONmcjFUTO/Hw4HZZVuRAyuKa0Nen8fsDzNgpAPPJS6yx4Q2vaQ3wX/x6OnYPQg=
notifications:
  slack:
    rooms:
      secure: CSMVCITuX8DLjDxHaxGaWftAEDn46qqwpIFv+MjBvA53SVjXtti/Pp0VVEiwHymupO4JVZWgwKenhUYsdk5qMJJX/xUAnZDr+YO/IfAqPaeqU2MpticvM+wSXcdfXDuvj+j8sZZyNSrJVmDV3/YWPWRVr5b4TCHHR70LQh2HcNYvauEZacAgbstcUIkzhMln/FV1EUTRedznI1Ta0EXWDXpWpzHz0VZfUqT20TMn4ynQs4IFqmhd87RZZYDa7uD5/k3uCTAZFWPnr1AMS7x2hLgZZsfLPRKsCTTfUPuFS2uB/OqmkuHm3GthLy0pWFQhKszETF7hmpQKJes2AMRFrexESetcmg7oyo6HmEasONNcBLt5rrohL4bW7xZibYz/Ewd9kQd5juQQh47pHvmr0C357MAaFBB1nLNBeMKs+QhPJWz6OgcZ2bDv5s+Vk8cq82LqnhgWi61sjZVs9Ib3yiCwaAYrUjMY4OZ7ltO2O7nxHsd9K0vahEuGzTgAbIeNhJ3mrD5tncYEpbRK/sgi4xV9x48iMIbevQII4om2/xSaPpVmfzzvcPODHWG6meWVh143iRehjOvJWKBQOu/PjPL3XdiGy++MYrENNpxiQQFp5O3csWTl9dvKGFmnzoEovtV1os0cDcl5CCvUAXOQE/6ad6n2hJpslnGT2bGbFFE=
